<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Lua.xsl"?>
<!DOCTYPE document [
	  <!ELEMENT document (section*,triggers,tables,types,section*)>
	  <!ATTLIST document title CDATA #REQUIRED>
	  
	  <!ELEMENT triggers (description?,(function*))>
	  <!ATTLIST triggers id ID #REQUIRED>
	  <!ELEMENT tables (description*,(table|accessor|enum|enum-accessor)*)>
	  <!ATTLIST tables id ID #REQUIRED>
	  <!ELEMENT types (description*)>
	  <!ATTLIST types id ID #REQUIRED>

	  <!ELEMENT section (description?,(section*))>
	  <!ATTLIST section name CDATA #REQUIRED>
	  <!ATTLIST section id ID #REQUIRED>
	  
	  <!ELEMENT table ((description?),(function|function-variable|subtable|subtable-accessor|variable)*)>
	  <!ATTLIST table name ID #REQUIRED>
	  <!ATTLIST table singleton (true|false) 'false'>

	  <!ELEMENT subtable ((alias*),(description?),(length?),(index?),(call?),(function|subtable|variable|note)*)>
	  <!ATTLIST subtable name CDATA #REQUIRED>
	  <!ATTLIST subtable classname ID #REQUIRED>

	  <!ELEMENT subtable-accessor ((alias?),(description?),(function|subtable|variable)*)>
	  <!ATTLIST subtable-accessor name CDATA #REQUIRED>
	  <!ATTLIST subtable-accessor classname ID #REQUIRED>
	  <!ATTLIST subtable-accessor index CDATA #REQUIRED>

	  <!ELEMENT description ANY>
	  <!ELEMENT br EMPTY>
	  <!ELEMENT p ANY>
	  <!ELEMENT pre ANY>

	  <!ELEMENT function ((description?),(argument*),(return*),(note*))>
	  <!ATTLIST function name CDATA #REQUIRED>
	  <!ATTLIST function access (local-player|all) 'all'>
	  <!ATTLIST function return (single|variant) 'single'>

	  <!ELEMENT function-variable ((description?),(argument),(type))>
	  <!ATTLIST function-variable name CDATA #REQUIRED>
	  <!ATTLIST function-variable classname CDATA #IMPLIED>

	  <!ELEMENT argument (description?,type)>
	  <!ATTLIST argument name CDATA #REQUIRED>
	  <!ATTLIST argument required (true|false) 'true'>

	  <!ELEMENT return (type)>

	  <!ELEMENT variable ((alias*), (description?),(type),(note*))>
	  <!ATTLIST variable name CDATA #REQUIRED>
	  <!ATTLIST variable access (read-only|read-write|local-player|write-only) "read-write">
	  <!ATTLIST variable version CDATA #IMPLIED>

	  <!ELEMENT accessor ((description?),(length?),(index?),(call?),(function)*)>
	  <!ATTLIST accessor name ID #REQUIRED>
	  <!ATTLIST accessor contains IDREF #REQUIRED>

	  <!ELEMENT enum-accessor ((description?),(length?),(index?),(call?))>
	  <!ATTLIST enum-accessor name ID #REQUIRED>
	  <!ATTLIST enum-accessor contains IDREF #REQUIRED>
	  <!ATTLIST enum-accessor nice-name CDATA #IMPLIED>
	  
	  <!ELEMENT enum ((description?),(function|function-variable|subtable|variable)*,(mnemonics?))>
	  <!ATTLIST enum name ID #REQUIRED>

	  <!ELEMENT mnemonics (mnemonic*)>
	  <!ELEMENT mnemonic EMPTY>

	  <!ATTLIST mnemonic name CDATA #REQUIRED>

	  <!ELEMENT length (description?)>
	  <!ELEMENT index ((description?),(type?))>
	  <!ELEMENT call (description?)>
	  <!ELEMENT type (#PCDATA)>
	  <!ELEMENT alias (#PCDATA)>
	  <!ELEMENT note (#PCDATA)>
	  <!ATTLIST note version CDATA #IMPLIED>
	  ]>
<document title="Aleph One Lua Scripters’ Guide">
  <section name="General" id="general">
    <section name="What is This?" id="what_is_this">
      <description>
		<p>This is a reference for writing Lua scripts to work in Aleph One. It lists every trigger and table available to Lua scripts. It is expected that Lua functionality will grow in Aleph One, and as it does, so will this document. Not everything here is completely documented, and any help fixing that would be appreciated.</p>
		<p>This is not a reference for Lua itself - see lua.org for that.</p>
      </description>
    </section>
    <section name="Running a Script" id="running_a_script">
      <description>
		<p>There are three ways to get a script to run - by embedding it in a level, by selecting a solo script in the Environment Preferences, or by selecting a script at the gather network game dialog.</p>
		<p>To embed a script in a level, use a tool such as Atque. Use embedded Lua scripts only for map specific features, not for modifying game types. For instance, it may be tempting to embed the latest version of the Lua CTF script in a map designed only for playing CTF; however, this would prevent the user from using a later version of CTF if it were to come out, or from using another net script that works on CTF maps. Some older scenarios use Lua scripts in TEXT resources, but this is no longer recommended since they are not transmitted in net games.</p>
		<p>To use a solo script, check the "Use Solo Script" box in Environment Preferences, and choose the script file to use.</p>
		<p>To use a script via the network game dialog, put then script in a text file with the extension .lua. Then, at the gather network game dialog, select "use script", then select your script file.</p>
      </description>
    </section>
    <section name="Units" id="units">
      <description>
		<p>The unit for distance we use is World Units (WU) These are the same values you’d see in Forge or with F10 location display, and 1/1024 of what A1 uses internally and what you’d see in Pfhorte.</p>
		<p>Units for speed are . . . well let’s say they’re messy. :) Lua speeds are expressed in World Units per tick (a tick is 1/30 of a second). Forge claims to use WU per sec, but it actually uses 0.87890625 WU per sec (which equals 30 internal units per tick). The following example illustrates the various conversions:</p>
		<ul>
		  <li><b style="display: inline-block; width: 10em; text-align: right">Actual:</b> 7.5 World Units per second</li>
		  <li><b style="display: inline-block; width: 10em; text-align: right">A1 internal:</b> 256 units per tick (7.5 * 1024 / 30)</li>
		  <li><b style="display: inline-block; width: 10em; text-align: right">Lua:</b> 0.25 WU per tick (7.5 / 30)</li>
		  <li><b style="display: inline-block; width: 10em; text-align: right">Forge:</b> 8.53 "WU per second" ((7.5 * 1024 / 30) / 30)</li>
		</ul>
      </description>
    </section>
	<section name="Net Games and Films" id="sync">
	  <description>
		<p>Aleph One net games distribute a set of player inputs, which are applied to each distributed game world or to the game world in the film being played back. There is a separate copy of the Lua script running on each player’s machine. This means that in order to prevent net games from going out of sync, or films from playing back incorrectly, each of the separately running Lua scripts needs to manipulate the world the exact same way.</p>
		<p>For example, if one player’s Lua script creates a monster, that monsters actions in the game are controlled by the random seed established at the beginning of the game. So, the other players’ scripts must create the same monster the same way, or the net game will go out of sync.</p>
		<p>Usually this is not a problem, as long as scripters avoid functions marked with the "local player" tag, and the two local random functions, which will return different results on different machines. The <code>global_random</code> and <code>random</code> functions will return the same number on different machines, as long as they are called the same number of times, so they are safe to use for net games.</p>
		<p>These rules apply to film playback as well; films will only play back if scripts behave exactly the same way as when the film was recorded</p>
		<p>A few accessors, such as Ephemera and Fog were designed to be used on a "local player" basis without breaking films or net. For instance, it would be safe to programmatically disable fog when a player zooms in by checking <code>Players.local_player.zoom_active</code>--because the mere presence of fog will not cause a net game or film to go out of sync. Likewise, Ephemera can be created based on the Ephemera.quality setting, which will vary from machine to machine. A script that only uses Ephemera can be turned on and off and film playback will be unaffected.</p>
		<p>When using local-safe accessors like Ephemera and Fog, it is important to use the matching <code>random_local</code> function, because it will not affect the progression of the ordinary random functions.</p>
		<p>If this is confusing to you, it would be safest simply to avoid using anything marked with the "local player" tag, as well as the two local random functions and Ephemera.</p>
	  </description>
	</section>
    <section name="Loading Collections" id="loading_collections">
      <description>
		<p>A Lua script can ask for the engine to load collections it might otherwise not load; for instance, in order to be able to spawn defenders and compilers on a map that might not have them otherwise, add the indices for those collections to the global table CollectionsUsed:
		</p><pre>CollectionsUsed = { 10, 16 }</pre>
      </description>
    </section>
    <section name="Persistence" id="persistence">
      <description>
		<p>Lua scripts are only active during a single level. If the user jumps to a new level, or restores from a saved game, the script is restarted in a clean state.</p>
		<p>It is now possible to pass data across level jumps, by using the Game.restore_passed() function. This function will restore any custom fields (see the "Custom Fields" section of "Using Tables" below) in the Players or Game tables that were set immediately prior to the last level jump. Note that in order for data to survive multiple level jumps, Game.restore_passed() must be called after each level jump. Game.restore_passed() will not restore data from saved games.</p>
		<p>It is also possible to restore data from saved games. The Game.restore_saved() function will restore all custom fields in use at the time the game was saved.</p>
		<p>Only numbers, strings, booleans, and tables (including Aleph One’s built-in userdata tables) can be restored.</p>
      </description>
    </section>
  </section>
  <triggers id="triggers">
    <description>These are functions scripts can define which Aleph One will call at specific times or events. For example, to regenerate health:
	<span class="pre">Triggers = {}
	function Triggers.idle()
	for p in Players() do 
    if p.life &lt; 150 and not p.dead then 
    p.life = p.life + 1
    end
	end
	end
	</span>
	Calling Triggers = {} at the beginning of the script removes the compatibility triggers installed for old Lua scripts, speeding up execution of new scripts.
	</description>
    <function name="init">
      <description>at beginning of level</description>
      <argument name="restoring_game">
		<description>true if restoring from a saved game</description>
		<type>boolean</type>
      </argument>
    </function>
    <function name="cleanup">
      <description>at end of the level</description>
      <note>primarily this is intended as a last chance for changing netgame scores before the postgame carnage report.</note>
    </function>
    <function name="idle">
      <description>at each tick, before physics and such</description>
    </function>
    <function name="postidle">
      <description>at each tick, after physics and such, but before rendering</description>
    </function>
    <function name="start_refuel">
      <description>whenever a player starts to use a refuel panel</description>
      <argument name="class"><type>control_panel_class</type></argument>
      <argument name="player"><type>player</type></argument>
      <argument name="side"><type>side</type></argument>
    </function>
    <function name="end_refuel">
      <description>whenever a player stops using a refuel panel</description>
      <argument name="class"><type>control_panel_class</type></argument>
      <argument name="player"><type>player</type></argument>
      <argument name="side"><type>side</type></argument>
    </function>
    <function name="tag_switch">
      <description>whenever a player uses a tag switch</description>
      <argument name="tag"><type>tag</type></argument>
      <argument name="player"><type>player</type></argument>
      <argument name="side"><type>side</type></argument>
      <note>not called when a projectile (e.g., fists) toggles a tag switch</note>
      <note>side is only valid in version 20111201 and newer</note>
    </function>
    <function name="light_switch">
      <description>whenever a player uses a light switch</description>
      <argument name="light"><type>light</type></argument>
      <argument name="player"><type>player</type></argument>
      <argument name="side"><type>side</type></argument>
      <note>not called when a projectile (e.g., fists) toggles a light switch</note>
      <note>side is only valid in version 20111201 and newer</note>
    </function>
    <function name="platform_switch">
      <description>whenever a player uses a platform switch</description>
      <argument name="polygon">
		<type>polygon</type>
		<description>polygon of the platform being toggled</description>
      </argument>
      <argument name="player"><type>player</type></argument>
      <argument name="side"><type>side</type></argument>
      <note>not called when a projectile (e.g., fists) toggles a platform switch</note>
      <note>side is only valid in version 20111201 and newer</note>
    </function>
    <function name="projectile_switch" version="20111201">
      <description>whenever a projectile toggles a switch</description>
      <argument name="projectile">
		<type>projectile</type>
		<description>projectile that toggled the switch</description>
      </argument>
      <argument name="side">
		<type>side</type>
		<description>side containing switch being toggled</description>
      </argument>
    </function>
    <function name="terminal_enter">
      <description>whenever a player starts using a terminal</description>
      <argument name="terminal"><type>terminal</type></argument>
      <argument name="player"><type>player</type></argument>
    </function>
    <function name="terminal_exit">
      <description>whenever a player stops using a terminal</description>
      <argument name="terminal"><type>terminal</type></argument>
      <argument name="player"><type>player</type></argument>
    </function>
    <function name="pattern_buffer">
      <description>whenever a player uses a pattern buffer</description>
      <argument name="side"><type>side</type></argument>
      <argument name="player"><type>player</type></argument>
    </function>
    <function name="got_item">
      <description>whenever a player picks up an item</description>
      <argument name="type"><type>item_type</type></argument>
      <argument name="player"><type>player</type></argument>
      <note>also whenever a player gets an item when a script calls .items.add()</note>
    </function>
    <function name="light_activated">
      <description>whenever a light is activated or deactivated</description>
      <argument name="light"><type>light</type></argument>
    </function>
    <function name="platform_activated">
      <description>whenever a platform is activated or deactivated</description>
      <argument name="polygon"><type>polygon</type></argument>
    </function>
    <function name="player_revived">
      <description>whenever a player revives (presumably only happens in a netgame)</description>
      <argument name="player"><type>player</type></argument>
    </function>
    <function name="player_killed">
      <description>whenever a player dies</description>
      <argument name="player"><type>player</type></argument>
      <argument name="aggressor_player">
		<description>the player who killed player, possibly himself (suicide) (can be nil)</description>
	  <type>player</type></argument>
      <argument name="action">
		<description>dying soft, dying hard, or dying flaming</description>
	  <type>monster_action</type></argument>
      <argument name="projectile">
		<description>the projectile that delivered the final blow (can be nil)</description>
	  <type>projectile</type></argument>
    </function>
    <function name="player_damaged">
      <description>whenever a player has taken damage, but before he dies if applicable. The player’s suit energy or oxygen may be negative when this trigger is called; if it still is when the trigger returns, it will be set to 0. The player’s suit energy is tested again after this trigger returns, so a script may prevent a player’s death
      </description>
      <argument name="victim">
		<type>player</type>
      </argument>
      <argument name="aggressor_player">
		<description>player who got the kill (can be nil)</description>
		<type>player</type>
      </argument>
      <argument name="aggressor_monster">
		<description>monster that got the kill (can be nil)</description>
		<type>monster</type>
      </argument>
      <argument name="damage_type">
		<description>e.g. "fists"</description>
		<type>damage_type</type>
      </argument>
      <argument name="damage_amount">
		<description>the amount recently subtracted from the player. If "oxygen drain", damage_amount was assessed against player’s oxygen; otherwise against player’s suit energy</description>
		<type>number</type>
      </argument>
      <argument name="projectile">
		<description>the projectile that delivered the damage (can be nil)</description>
		<type>projectile</type>
      </argument>
    </function>
    <function name="monster_damaged" version="20100118">
      <description>whenever a monster is damaged, but before it dies if applicable. The monster’s vitality may be negative when this trigger is called. Ther monster’s vitality will be tested again after this trigger returns, so a script may prevent a monster’s death</description>
      <argument name="monster">
		<type>monster</type>
      </argument>
      <argument name="aggressor_monster">
		<description>the monster that caused the damage (can be nil)</description>
		<type>monster</type>
      </argument>
      <argument name="damage_type">
		<description>e.g. "fists"</description>
		<type>damage_type</type>
      </argument>
      <argument name="damage_amount">
		<description>the amount recently subtracted from the monster’s vitality</description>
		<type>number</type>
      </argument>
      <argument name="projectile">
		<description>the projectile that delivered the damage (can be nil)</description>
		<type>projectile</type>
      </argument>
    </function>
    <function name="monster_killed">
      <description>whenever a monster dies</description>
      <argument name="monster"><type>monster</type></argument>
      <argument name="aggressor_player">
		<description>player who killed it (can be nil)</description>
		<type>player</type>
      </argument>
      <argument name="projectile">
		<description>projectile that delivered the final blow (can be nil)</description>
		<type>projectile</type>
      </argument>
      <note>called after a monster has taken lethal damage, but before it’s removed from the monster list</note>
      <note>you can use this to find out when a monster created with new_monster dies, but a monster discovered by Polygons.monsters() may have already taken lethal damage, so you may need to check for that case when using Polygons.monsters()</note>
    </function>
    <function name="item_created">
      <description>whenever an item is created and placed on the ground (or floating) somewhere</description>
      <argument name="item"><type>item</type></argument>
      <note>does not trigger on initial item placement because the initial item placement is done before Lua becomes initialised.</note>
    </function>
    <function name="projectile_created" version="20150619">
      <description>whenever a projectile is created</description>
      <argument name="projectile"><type>projectile</type></argument>
    </function>
    <function name="projectile_detonated">
      <description>whenever a projectile detonates, after it has done any area of effect damage</description>
      <argument name="type"><type>projectile_type</type></argument>
      <argument name="owner"><type>monster</type></argument>
      <argument name="polygon"><type>polygon</type></argument>
      <argument name="x"><type>WU</type></argument>
      <argument name="y"><type>WU</type></argument>
      <argument name="z"><type>WU</type></argument>
	  <argument name="t" version="20210408"><type>variant</type></argument>
	  <note>t can be a side, polygon_floor, polygon_ceiling, monster, scenery, polygon; see Polygon:check_collision for info on how to decode. It can also be nil, in the rare case a projectile detonates without hitting something</note>
    </function>
  </triggers>
  <section id="using_tables" name="Using Tables">
    <description><p>There are numerous tables (technically, userdata) defined in Aleph One which scripts can use to access objects in the game. A complete list is below.</p>
    <p>Unless otherwise specified, these tables are only valid inside the trigger calls listed above. Attempting to use them in the main body of a script may cause an error in this version or a future version of Aleph One.</p></description>
    <section id="custom" name="Custom Fields">
      <description><p>In a real Lua table, you can set any field you want. In order to help troubleshooting, Aleph One’s userdata tables will only accept the fields listed in the documentation below. However, by prepending an underscore, custom fields can be indexed. These custom fields will be associated with the object until it is destroyed.</p><pre>Players[0]._favorite_flavor = "chocolate"</pre></description>
    </section>
    <section id="table_indices" name="Index">
      <description><p>Each table has a read-only .index variable, that corresponds to the engine’s internal index.</p><pre>=Players[0].index<br/>0</pre></description>
    </section>
    <section id="table_is" name="is_ Functions">
      <description><p>Aleph One installs a set of boolean functions that can be used to recognize each of the userdata table types. For example, <code>is_monster(Monsters[1])</code> returns true. Each of these functions begins with the "is_" prefix.</p></description>
    </section>
  </section>
  <tables id="tables">
    <table name="annotation">
      <variable name="polygon">
		<description>polygon this annotation is associated with</description>
		<type>polygon</type>
		<note>can be nil</note>
		<note>an annotation is only shown when its polygon is visible on the overhead map</note>
      </variable>
      <variable name="text">
		<description>annotation text (64 characters max)</description>
		<type>string</type>
      </variable>
      <variable name="x">
		<type>WU</type>
      </variable>
      <variable name="y">
		<type>WU</type>
      </variable>
    </table>
    <table name="camera">
      <function name="activate">
		<description>activate camera for player</description>
		<argument name="player"><type>player</type></argument>
      </function>
      <function name="clear">
		<description>deletes all path points and angles</description>
      </function>
      <function name="deactivate">
		<description>deactivates camera</description>
      </function>
      <subtable name="path_angles" classname="lua_path_angles">
		<function name="new">
		  <description>adds a path angle</description>
		  <argument name="yaw"><type>angle</type></argument>
		  <argument name="pitch"><type>pitch</type></argument>
		  <argument name="time"><type>time</type></argument>
		</function>
      </subtable>
      <subtable name="path_points" classname="lua_path_points">
		<function name="new">
		  <description>adds a path point</description>
		  <argument name="x"><type>WU</type></argument>
		  <argument name="y"><type>WU</type></argument>
		  <argument name="z"><type>WU</type></argument>
		  <argument name="polygon"><type>polygon</type></argument>
		  <argument name="time"><type>time</type></argument>
		</function>
      </subtable>
    </table>
    <table name="effect">
      <function name="delete" version="20111201">
		<description>removes effect from map</description>
      </function>
      <variable name="facing" version="20111201">
		<description>direction effect is facing</description>
		<type>degrees</type>
      </variable>
      <function name="play_sound" version="20111201">
		<description>play sound coming from this effect</description>
		<argument name="sound"><type>sound</type></argument>
      </function>
      <variable name="polygon" access="read-only" version="20111201">
		<description>polygon the effect is in</description>
		<type>polygon</type>
      </variable>
      <function name="position" version="20111201">
		<description>sets position of effect</description>
		<argument name="x">
		<type>WU</type></argument>
		<argument name="y"><type>WU</type></argument>
		<argument name="z"><type>WU</type></argument>
		<argument name="polygon"><type>polygon</type></argument>
      </function>
      <variable name="type" access="read-only" version="20111201">
		<description>type of effect</description>
		<type>effect_type</type>
      </variable>
      <variable name="x" access="read-only" version="20111201">
		<type>WU</type>
      </variable>
      <variable name="y" access="read-only" version="20111201">
		<type>WU</type>
      </variable>
      <variable name="z" access="read-only" version="20111201">
		<type>WU</type>
      </variable>
    </table>
    <table name="endpoint">
      <variable name="x" access="read-only">
		<type>WU</type>
      </variable>
      <variable name="y" access="read-only">
		<type>WU</type>
      </variable>
    </table>
    <table name="game" singleton="true">
      <variable name="dead_players_drop_items" version="20150619">
        <description>whether dead players drop items</description>
        <type>boolean</type>
      </variable>
      <function name="deserialize" version="20200830">
        <description>deserializes s and returns the original Lua value</description>
        <argument name="s"><type>string</type></argument>
        <return><type>value</type></return>
        <note>see Game.serialize</note>
      </function>
      <variable name="difficulty" access="read-only">
		<description>the difficulty level</description>
		<type>difficulty_type</type>
      </variable>
      <function name="global_random">
		<description>returns a random number between 0 and n-1 from Aleph One’s original random number generator</description>
		<argument name="n"><type>number</type></argument>
		<return><type>number</type></return>
      </function>
      <variable name="kill_limit" access="read-only">
		<description>the game kill limit, or 0 if there is none</description>
		<type>number</type>
      </variable>
      <variable name="monsters_replenish" version="20111201">
		<description>whether monsters spawn or not; in a net game, this corresponds to the "Aliens" checkbox</description>
		<type>boolean</type>
		<note>this can suppress initial monster placement, if set to false directly when the script is loaded</note>
      </variable>
      <variable name="proper_item_accounting" version="20100118">
		<description>When true, the current item counts on the map are updated properly when Lua deletes map items and changes player inventories. This defaults to false to preserve film playback with older scripts. New scripts that manipulate items should always set this to true.</description>
		<type>boolean</type>
      </variable>
      <variable name="nonlocal_overlays" version="20200830">
		<description>When false, only the local player’s overlays are used, and only prints to the local player will be displayed. When true, the overlays and prints of whatever player is currently being viewed will apply. This defaults to false for compatibility with scripts that depend on the old behavior.</description>
		<type>boolean</type>
      </variable>
      <variable name="time_remaining" access="read-only">
		<description>the number of ticks until the game ends, or nil if there is no time limit</description>
		<type>number</type>
      </variable>
      <variable name="scoring_mode">
		<description>the current scoring mode (if the gametype is "custom")</description>
		<type>scoring_mode_type</type>
      </variable>
      <variable name="over" access="write-only">
		<description>Use this variable to override the game’s default scoring behavior. If set to false, the game will not end due to a score limit. If set to true, the game ends immediately. If left unset or if set to nil, the game will end if a score limit is reached. (Note that you cannot prevent the game from ending due to a time limit.)</description>
		<type>boolean</type>
      </variable>
      <function name="local_random">
		<description>returns a random number between 0 and n-1 from Aleph One’s original random number generator</description>
		<argument name="n"><type>number</type></argument>
		<return><type>number</type></return>
		<note>use only for local player effects (see Net Games and Films)</note>
      </function>
      <function name="random">
		<description>returns a random number between 0 and n-1 using a good random number generator</description>
		<argument name="n"><type>number</type></argument>
		<return><type>number</type></return>
      </function>
	  <function name="random_local" version="20210408">
		<description>returns a random number between 0 and n-1 using a good random number generator</description>
		<argument name="n"><type>number</type></argument>
		<return><type>number</type></return>
		<note>use only for local player effects (see Net Games and Films)</note>
	  </function>
	  <variable name="replay" access="read-only" version="20221126">
		<description>is the script being run during a film replay</description>
		<return><type>boolean</type></return>
		<note>use sparingly; altering the world differently during a replay than during live playback will cause the replay go out of sync</note>
	  </variable>
      <function name="restore_passed" version="20090909">